server:
  port: 4949
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dog?useUnicode=true&characterEncoding=utf8
    username: root
    password: qazwsx123
  redis:
    host: 127.0.0.1 # redis Hostname
    port: 6379 # redis端口
    database: 2